### ISSUE TITLE
[Android] App crashes on start up in release mode

### ISSUE THREAD

**Issue by iabdousd** [ja2375/add_2_calendar#104]
Hello, we are facing the following issue:

After adding the package to our project's pubspec.yaml and starting the app in release mode, it crashes immediately after it's ran with these logs:
```
[+2850 ms] E/AndroidRuntime(11387): FATAL EXCEPTION: ScionFrontendApi
[        ] E/AndroidRuntime(11387): Process: app.roamtogether.android, PID: 11387
[        ] E/AndroidRuntime(11387): java.lang.ExceptionInInitializerError
[        ] E/AndroidRuntime(11387):     at com.google.android.gms.measurement.internal.O2.<init>(Unknown Source:34)
[        ] E/AndroidRuntime(11387):     at com.google.android.gms.measurement.internal.a2.<init>(:3)
[        ] E/AndroidRuntime(11387):     at com.google.android.gms.measurement.internal.a2.G(:4)
[        ] E/AndroidRuntime(11387):     at com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.initialize(:2)
[        ] E/AndroidRuntime(11387):     at com.google.android.gms.internal.measurement.s0.a(:8)
[        ] E/AndroidRuntime(11387):     at com.google.android.gms.internal.measurement.E0.run(Unknown Source:12)
[        ] E/AndroidRuntime(11387):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[        ] E/AndroidRuntime(11387):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[        ] E/AndroidRuntime(11387):     at java.lang.Thread.run(Thread.java:923)
[        ] E/AndroidRuntime(11387): Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: F2.b.values []
[        ] E/AndroidRuntime(11387):     at java.lang.Enum.enumValues(Enum.java:270)
[        ] E/AndroidRuntime(11387):     at java.lang.Enum.access$000(Enum.java:61)
[        ] E/AndroidRuntime(11387):     at java.lang.Enum$1.create(Enum.java:277)
[        ] E/AndroidRuntime(11387):     at java.lang.Enum$1.create(Enum.java:275)
[        ] E/AndroidRuntime(11387):     at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
[        ] E/AndroidRuntime(11387):     at java.lang.Enum.getSharedConstants(Enum.java:289)
[        ] E/AndroidRuntime(11387):     at java.lang.Class.getEnumConstantsShared(Class.java:2428)
[        ] E/AndroidRuntime(11387):     at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
[        ] E/AndroidRuntime(11387):     at java.util.EnumMap.<init>(EnumMap.java:138)
[        ] E/AndroidRuntime(11387):     at F2.c.<init>(Unknown Source:7)
[        ] E/AndroidRuntime(11387):     at F2.c.<clinit>(Unknown Source:3)
[        ] E/AndroidRuntime(11387):     ... 9 more
[        ] E/AndroidRuntime(11387): Caused by: java.lang.NoSuchMethodException: F2.b.values []
[        ] E/AndroidRuntime(11387):     at java.lang.Class.getMethod(Class.java:2072)
[        ] E/AndroidRuntime(11387):     at java.lang.Class.getDeclaredMethod(Class.java:2050)
[        ] E/AndroidRuntime(11387):     at java.lang.Enum.enumValues(Enum.java:267)
[        ] E/AndroidRuntime(11387):     ... 19 more
```

Note: this only happens in Android and only in release mode.

**Comment by fvisticot** [comment]
Same issue, any workaround / update

**Comment by lyabs243** [comment]
I have the same issue.
Any update on this?

**Comment by Chonli** [comment]
I solve this issue with add a proguard file:
```
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
```

I follow instruction of this [post stackoverflow](https://stackoverflow.com/questions/20651575/android-release-apk-crash-with-java-lang-assertionerror-impossible-in-java-lang)
