### ISSUE TITLE
CastException

### ISSUE THREAD

**Issue by cearsmehul** [ja2375/add_2_calendar#43]
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
at com.javih.add2calendar.Add2CalendarPlugin.onMethodCall(**Add2CalendarPlugin.java:32**)

Full log is bellow :
 Failed to handle method call
 java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
 	at com.javih.add2calendar.Add2CalendarPlugin.onMethodCall(Add2CalendarPlugin.java:32)
 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:650)
 	at android.os.MessageQueue.nativePollOnce(Native Method)
 	at android.os.MessageQueue.next(MessageQueue.java:326)
 	at android.os.Looper.loop(Looper.java:160)
 	at android.app.ActivityThread.main(ActivityThread.java:6762)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by diegogarciar** [comment]
This bug has not been able to replicate, I will close the issue as it is very old and a lot has changed in the code, if you are still experiencing the issue, please let me know.
