### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Milvintsiss** [ja2375/add_2_calendar#75]
I'm using gradle 6.7.1.
I already build successfully the project with add2calendar some days ago and didn't change anything since.

I get the following error:
```
Note: /Users/milvintsiss/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/add_2_calendar-2.1.0/android/src/main/java/com/javih/add2calendar/Add2CalendarPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':add_2_calendar:compileDebugJavaWithJavac'.
> java.lang.IllegalAccessError: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x5659c3f) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x5659c3f

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by cmorsucci** [comment]
same issue

**Comment by diegogarciar** [comment]
Is there a specific reason as to why you are using this cradle version? New flutter projects are not created with this gradle version.

**Comment by diegogarciar** [comment]
I have migrated the package into a new template project, let me know if this solves your issue

**Comment by Milvintsiss** [comment]
@diegogarciar I have no time to try this now, but I will try this in the month for sure, thanks for your time :)

**Comment by Milvintsiss** [comment]
I tried and now I get this error:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/milvintsiss/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/add_2_calendar-2.1.1/android/build.gradle'

* What went wrong:
Could not compile build file '/Users/milvintsiss/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/add_2_calendar-2.1.1/android/build.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 60

  java.lang.IllegalArgumentException: Unsupported class file major version 60
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
       [...]
```

**Comment by diegogarciar** [comment]
Hi, sorry for the late response, it seems that the package is now using a higher graddle version, can you please specify yours?

**Comment by Milvintsiss** [comment]
Hi, sorry I was a little busy,
I retried today and I don't know if you updated something or if it was on my side but it seems to be working perfectly, thanks for your support and your work on this plugin!!
