### ISSUE TITLE
Unable to add event : Failed to handle method call

### ISSUE THREAD

**Issue by QuentinSc** [ja2375/add_2_calendar#87]
Hello anad thank you for your work.
Actually I have this error when calling Add2Calendar.addEvent2Cal method.

**My AndroidManifest is correcly updated with queries**
```
<queries>
        <intent>
            <action android:name="android.intent.action.INSERT" />
            <data android:mimeType="vnd.android.cursor.item/event" />
        </intent>
    </queries>

```
Did futter clean

Flutter 2.5.2
Android 11 Emulator, Android 8 Emulator
Add2Calendar 2.1.2

```
E/MethodChannel#add_2_calendar(16579): Failed to handle method call
E/MethodChannel#add_2_calendar(16579): kotlin.KotlinNullPointerException
E/MethodChannel#add_2_calendar(16579): 	at com.javih.add_2_calendar.Add2CalendarPlugin.onMethodCall(Add2CalendarPlugin.kt:40)
E/MethodChannel#add_2_calendar(16579): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#add_2_calendar(16579): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#add_2_calendar(16579): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#add_2_calendar(16579): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#add_2_calendar(16579): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#add_2_calendar(16579): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#add_2_calendar(16579): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#add_2_calendar(16579): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#add_2_calendar(16579): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#add_2_calendar(16579): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (16579): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, null, null, kotlin.KotlinNullPointerException
E/flutter (16579): 	at com.javih.add_2_calendar.Add2CalendarPlugin.onMethodCall(Add2CalendarPlugin.kt:40)
E/flutter (16579): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (16579): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/flutter (16579): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/flutter (16579): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (16579): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (16579): 	at android.os.Looper.loop(Looper.java:183)
E/flutter (16579): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter (16579): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (16579): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (16579): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (16579): )
E/flutter (16579): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:607
E/flutter (16579): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
E/flutter (16579): <asynchronous suspension>
E/flutter (16579):
```

**Comment by diegog-sf** [comment]
Hello, Have you added the new `query` to your manifest?

**Comment by QuentinSc** [comment]
Hello @diegog-sf , yep, I've read all the readme

**Comment by diegogarciar** [comment]
Can you try `flutter clean`?

**Comment by QuentinSc** [comment]
Yep already did too.

On a real device, release builder from CI/CD, nothing happen when I try to add event
With 2.0.2 version it opened the calendar application
