### ISSUE TITLE
Android relase mode: Not opening app.

### ISSUE THREAD

**Issue by terrasuscompany** [ja2375/add_2_calendar#89]
app doesn't started. If I remove plugin its working fine. 

 FATAL EXCEPTION: main
E/AndroidRuntime(25006): Process: com.terrasus.barcodescanner, PID: 25006
E/AndroidRuntime(25006): java.lang.RuntimeException: java.lang.NoSuchMethodException: e.f.e.e.values []
E/AndroidRuntime(25006):        at java.lang.Enum.enumValues(Enum.java:270)
E/AndroidRuntime(25006):        at java.lang.Enum.access$000(Enum.java:61)
E/AndroidRuntime(25006):        at java.lang.Enum$1.create(Enum.java:277)
E/AndroidRuntime(25006):        at java.lang.Enum$1.create(Enum.java:275)
E/AndroidRuntime(25006):        at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
E/AndroidRuntime(25006):        at java.lang.Enum.getSharedConstants(Enum.java:289)
E/AndroidRuntime(25006):        at java.lang.Class.getEnumConstantsShared(Class.java:2428)
E/AndroidRuntime(25006):        at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
E/AndroidRuntime(25006):        at java.util.EnumMap.<init>(EnumMap.java:138)
E/AndroidRuntime(25006):        at com.journeyapps.barcodescanner.z.a(Unknown Source:4)
E/AndroidRuntime(25006):        at com.journeyapps.barcodescanner.BarcodeView.E(:2)
E/AndroidRuntime(25006):        at com.journeyapps.barcodescanner.BarcodeView.I(Unknown Source:20)
E/AndroidRuntime(25006):        at com.journeyapps.barcodescanner.BarcodeView.w(Unknown Source:0)
E/AndroidRuntime(25006):        at com.journeyapps.barcodescanner.p.A(Unknown Source:28)
E/AndroidRuntime(25006):        at com.journeyapps.barcodescanner.p.B(Unknown Source:48)
E/AndroidRuntime(25006):        at com.journeyapps.barcodescanner.p.d(:5)
E/AndroidRuntime(25006):        at com.journeyapps.barcodescanner.l.handleMessage(Unknown Source:13)
E/AndroidRuntime(25006):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(25006):        at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(25006):        at android.app.ActivityThread.main(ActivityThread.java:8061)
E/AndroidRuntime(25006):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25006):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/AndroidRuntime(25006):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/AndroidRuntime(25006): Caused by: java.lang.NoSuchMethodException: e.f.e.e.values []
E/AndroidRuntime(25006):        at java.lang.Class.getMethod(Class.java:2072)
E/AndroidRuntime(25006):        at java.lang.Class.getDeclaredMethod(Class.java:2050)
E/AndroidRuntime(25006):        at java.lang.Enum.enumValues(Enum.java:267)

**Comment by wwwhttpru** [comment]
Is there a solution to the problem?
